class_name RunState
extends RefCounted

## preload (no class_name directo): scripts class_name recién creados
## necesitan que el editor escanee el global class cache al menos una vez;
## en este proyecto se corre siempre headless por CLI, así que preload
## evita depender de ese timing.
const _EquipmentSetResolver = preload("res://scripts/equipment/equipment_set_resolver.gd")
const _RouteBranchData = preload("res://scripts/board/route_branch_data.gd")

const BASE_MAX_HEALTH := 100
const BASE_CURRENT_HEALTH_OFFSET := 20
const BASE_ATTACK := 20
const BASE_DEFENSE := 5
const NORMAL_COMBAT_ASH := 5
const ELITE_COMBAT_ASH := 10
const BOSS_VICTORY_ASH := 50

## Active Run Persistence — stable identity for this expedition, generated
## once at creation (see RunManager.start_new_run()), never regenerated by
## deserialization. Doubles as the reward-deposit idempotency key
## (SaveManager.deposit_run() / ProfileData.last_deposited_run_id).
var run_id: String = ""
var started_at_unix: int
var biome_id: StringName
var biome_data: BiomeData
var board_seed: int = BoardGenerator.NO_SEED
var board_tile_sequence: Array[int] = []
var last_normal_encounter_signature: StringName = &""
var biome_intro_shown: bool = false
var active_skill_id: StringName = ActiveSkillCatalog.DEFAULT_SKILL_ID
var equipped_skill_ids: Array[StringName] = []
var equipped_companion_id: StringName = &""
var player_name: String = "Ashen Wanderer"
var max_health: int = BASE_MAX_HEALTH
var current_health: int = BASE_MAX_HEALTH - BASE_CURRENT_HEALTH_OFFSET
var attack: int = BASE_ATTACK
var defense: int = BASE_DEFENSE
var board_position: int = 0
var board_locked: bool = false
## Estado transitorio de agency; vive solo durante la run activa y no migra perfil.
var route_choice_count: int = 0
var route_option_a: int = -1
var route_option_b: int = -1
var chosen_destination: int = -1
var chosen_tile_type: int = -1
var route_choice_cooldown: bool = false
## Bifurcaciones pre-generadas de esta run: fork_index -> RouteBranchData.
var route_branches: Dictionary = {}
## Carril activo mientras board_position está dentro de una bifurcación
## (RouteBranchData.NONE/ROUTE_A/ROUTE_B). No migra perfil.
var active_branch: int = _RouteBranchData.NONE
var active_fork_index: int = -1
var combats_won: int = 0
var elites_won: int = 0
var events_resolved: int = 0
var treasures_found: int = 0
## Memoria local de decisiones narrativas; nunca se copia a ProfileData.
var event_flag_ids: Array[StringName] = []
var seen_event_ids: Array[StringName] = []
var resolved_event_positions: Array[int] = []
var resolved_treasure_positions: Array[int] = []
var pending_treasure_position: int = -1
var pending_treasure_offers: Array[Dictionary] = []
var upgrades_obtained: int = 0
var run_completed: bool = false
var run_ash: int = 0
var biome_material_earned: int = 0
var rewards_deposited: bool = false
## Resumen de progresión permanente rellenado al depositar Results.
var player_xp_earned: int = 0
var player_level_before: int = PlayerProgressionConfig.START_LEVEL
var player_level_after: int = PlayerProgressionConfig.START_LEVEL
var player_xp_before: int = 0
var player_xp_after: int = 0
var player_levels_gained: int = 0
var completed_milestone_ids_this_run: Array[StringName] = []
var milestone_ash_awarded: int = 0
var loot_rolled: bool = false
var pending_loot_id: String = ""
var duplicate_converted_id: StringName = &""
var duplicate_ash_awarded: int = 0
var boss_reward_id: StringName = &""
var boss_reward_applied: bool = false
var boss_chest_id: StringName = &""
var boss_chest_awarded: bool = false
var guardian_sigils_awarded: int = 0
var loot_minimum_rarity: EquipmentData.Rarity = EquipmentData.Rarity.COMMON
var loot_rarity_upgrades: int = 0
var active_boons: Dictionary[StringName, int] = {}
var skill_augments: Dictionary[StringName, int] = {}
var active_synergy_ids: Array[StringName] = []
var activated_synergy_ids: Array[StringName] = []
var pending_synergy_announcement_ids: Array[StringName] = []
var upgrade_rerolls: int = 2
var reward_offers_generated: int = 0
var phoenix_blood_empowered: bool = false
## Recurso transitorio de la run; no se persiste en ProfileData ni requiere migración.
var combat_energy_carryover: int = 0
var run_level: int = RunLevelConfig.START_LEVEL
var current_xp: int = 0
var total_xp_gained: int = 0
var pending_level_ups: int = 0
var level_up_choices_generated: int = 0
var pending_level_up_option_ids: Array[StringName] = []
var run_level_upgrade_stacks: Dictionary[StringName, int] = {}
var equipped_weapon_id: StringName = &""
var equipped_armor_id: StringName = &""
var owned_equipment_ids_at_start: Array[String] = []
var equipment_passive_ids: Array[StringName] = []
var equipment_crit_chance: float = 0.0
var equipment_crit_damage_bonus: float = 0.0
var equipment_ember_gain_bonus: float = 0.0
var equipment_healing_power_bonus: float = 0.0
var equipment_skill_damage_bonus: float = 0.0
## Equipment 2.0 Fase 1 — affinity_id (genérico, ver AffinityResolver) -> %
## de resistencia acumulada de CHEST/HEAD/CAPE/RELIC equipados. Consumido
## por combat.gd:_resolve_elemental_damage cuando el jugador es el target.
var equipment_resistance_bonuses: Dictionary[StringName, float] = {}
var telemetry_started: bool = false
var telemetry_finished: bool = false
var telemetry_started_unix: int = 0
var telemetry_skill_uses: Dictionary[String, int] = {}
var telemetry_synergy_ids: Array[StringName] = []
var telemetry_last_boss_id: StringName = &""
var telemetry_boss_phase_reached: int = 0
var starting_option_id: StringName = &""


func get_reward_affinity_count(affinity: UpgradeData.Affinity) -> int:
	var total: int = get_affinity_count(affinity)
	if MetaUnlockCatalog.get_affinity(starting_option_id) == affinity:
		total += 1
	return total


func _init() -> void:
	started_at_unix = int(Time.get_unix_time_from_system())


func heal(amount: int) -> int:
	var equipment_multiplier: float = 1.0 + equipment_healing_power_bonus
	var effective_amount: int = BiomeModifierResolver.effective_healing(amount, biome_data, equipment_multiplier)
	return heal_structural(effective_amount)


func has_event_flag(flag_id: StringName) -> bool:
	return flag_id in event_flag_ids


func add_event_flag(flag_id: StringName) -> void:
	if not flag_id.is_empty() and flag_id not in event_flag_ids:
		event_flag_ids.append(flag_id)


func heal_structural(amount: int) -> int:
	var previous_health: int = current_health
	current_health = mini(current_health + maxi(0, amount), max_health)
	return current_health - previous_health


func get_xp_to_next_level() -> int:
	return RunLevelConfig.xp_required_for_level(run_level)


func add_run_xp(amount: int) -> int:
	if amount <= 0:
		return 0
	total_xp_gained += amount
	current_xp += amount
	var levels_gained: int = 0
	while run_level < RunLevelConfig.MAX_RUN_LEVEL:
		var requirement: int = get_xp_to_next_level()
		if requirement <= 0 or current_xp < requirement:
			break
		current_xp -= requirement
		run_level += 1
		pending_level_ups += 1
		levels_gained += 1
	if run_level >= RunLevelConfig.MAX_RUN_LEVEL:
		current_xp = 0
	return levels_gained


func get_run_level_upgrade_count(upgrade_id: StringName) -> int:
	return int(run_level_upgrade_stacks.get(upgrade_id, 0))


func record_run_level_upgrade(upgrade: UpgradeData) -> void:
	if upgrade == null:
		return
	var count: int = get_run_level_upgrade_count(upgrade.id)
	run_level_upgrade_stacks[upgrade.id] = mini(upgrade.max_stacks, count + 1)
	upgrades_obtained += 1
	pending_level_ups = maxi(0, pending_level_ups - 1)
	pending_level_up_option_ids.clear()
	recalculate_synergies()


func add_boon(boon_id: StringName, amount: int = 1) -> int:
	if boon_id.is_empty() or amount <= 0:
		return get_boon_count(boon_id)
	var boon: UpgradeData = UpgradeCatalog.get_by_id(boon_id)
	var maximum: int = boon.max_stacks if boon != null else 99
	active_boons[boon_id] = mini(maximum, get_boon_count(boon_id) + amount)
	recalculate_synergies()
	return active_boons[boon_id]


func next_reward_offer_seed(context: StringName) -> int:
	var seed: int = BuildRewardResolver.make_seed(self, context, reward_offers_generated)
	reward_offers_generated += 1
	return seed


func get_boon_count(boon_id: StringName) -> int:
	return int(active_boons.get(boon_id, 0))


func add_skill_augment(augment_id: StringName, amount: int = 1) -> int:
	var augment: SkillAugmentData = SkillAugmentCatalog.get_by_id(augment_id)
	if augment == null or augment.skill_id not in equipped_skill_ids or amount <= 0:
		return get_skill_augment_count(augment_id)
	var next_count: int = mini(augment.max_stacks, get_skill_augment_count(augment_id) + amount)
	skill_augments[augment_id] = next_count
	recalculate_synergies()
	return next_count


func recalculate_synergies() -> Array[StringName]:
	var newly_activated: Array[StringName] = SynergyResolver.recalculate(self)
	if telemetry_started:
		for synergy_id: StringName in newly_activated:
			TelemetryManager.track_synergy_activated(self, synergy_id)
	return newly_activated


func consume_pending_synergy_announcements() -> Array[StringName]:
	var result: Array[StringName] = pending_synergy_announcement_ids.duplicate()
	pending_synergy_announcement_ids.clear()
	return result


func get_skill_augment_count(augment_id: StringName) -> int:
	return int(skill_augments.get(augment_id, 0))


func get_affinity_count(affinity: UpgradeData.Affinity) -> int:
	var total: int = 0
	for boon_id: StringName in active_boons:
		var upgrade: UpgradeData = UpgradeCatalog.get_by_id(boon_id)
		if upgrade != null and upgrade.category == UpgradeData.Category.PASSIVE and upgrade.affinity == affinity:
			total += get_boon_count(boon_id)
	return total


func apply_permanent_upgrades(profile: ProfileData) -> void:
	equipped_weapon_id = &""
	equipped_armor_id = &""
	equipment_passive_ids.clear()
	equipment_crit_chance = 0.0
	equipment_crit_damage_bonus = 0.0
	equipment_ember_gain_bonus = 0.0
	equipment_healing_power_bonus = 0.0
	equipment_skill_damage_bonus = 0.0
	equipment_resistance_bonuses.clear()
	max_health = BASE_MAX_HEALTH + PermanentUpgradeConfig.get_total_bonus(
		PermanentUpgradeConfig.UpgradeType.VITALITY,
		profile.permanent_health_level,
	)
	current_health = max_health - BASE_CURRENT_HEALTH_OFFSET
	attack = BASE_ATTACK + PermanentUpgradeConfig.get_total_bonus(
		PermanentUpgradeConfig.UpgradeType.MIGHT,
		profile.permanent_attack_level,
	)
	defense = BASE_DEFENSE + PermanentUpgradeConfig.get_total_bonus(
		PermanentUpgradeConfig.UpgradeType.GUARD,
		profile.permanent_defense_level,
	)
	var equipped_ids: Array[String] = [profile.equipped_weapon_id, profile.equipped_armor_id]
	for slot_name: String in profile.equipped_slots:
		equipped_ids.append(profile.equipped_slots[slot_name])
	var equipped_set_ids: Array[StringName] = []
	for equipped_id: String in equipped_ids:
		_apply_equipped_item(equipped_id, int(profile.equipment_refinement.get(equipped_id, 0)))
		var equipped_item: EquipmentData = EquipmentCatalog.get_by_id(equipped_id)
		if equipped_item != null and not equipped_item.set_id.is_empty():
			equipped_set_ids.append(equipped_item.set_id)
	_EquipmentSetResolver.apply_set_bonuses(self, equipped_set_ids)
	current_health = maxi(1, max_health - BASE_CURRENT_HEALTH_OFFSET)


func prepare_loot(is_victory: bool) -> void:
	if loot_rolled:
		return
	loot_rolled = true
	var item: EquipmentData = EquipmentCatalog.roll_run_loot(
		is_victory,
		loot_minimum_rarity,
		loot_rarity_upgrades,
		owned_equipment_ids_at_start,
		biome_id,
	)
	pending_loot_id = "" if item == null else String(item.id)


func _apply_equipped_item(equipment_id: String, refinement_level: int = 0) -> void:
	var item: EquipmentData = EquipmentCatalog.get_by_id(equipment_id)
	if item == null:
		return
	max_health += item.max_health_bonus
	attack += item.attack_bonus
	defense += item.defense_bonus
	# Refinamiento: WEAPON aporta a ATQ, el resto de los 5 slots (CHEST/HEAD/
	# CAPE/RELIC) aporta a DEF — mismo criterio binario que ya existía para
	# WEAPON/ARMOR, generalizado. INITIAL TUNING, sin balance final.
	var refinement_bonus: int = RefinementConfig.get_primary_bonus(refinement_level)
	if item.slot == EquipmentData.Slot.WEAPON:
		attack += refinement_bonus
		equipped_weapon_id = item.id
	else:
		defense += refinement_bonus
		if item.slot == EquipmentData.Slot.CHEST:
			equipped_armor_id = item.id
	if not item.resistance_affinity_id.is_empty():
		equipment_resistance_bonuses[item.resistance_affinity_id] = float(equipment_resistance_bonuses.get(item.resistance_affinity_id, 0.0)) + item.resistance_bonus
	equipment_crit_chance += item.crit_chance
	equipment_crit_damage_bonus += item.crit_damage_bonus
	equipment_ember_gain_bonus += item.ember_gain_bonus
	equipment_healing_power_bonus += item.healing_power_bonus
	equipment_skill_damage_bonus += item.skill_damage_bonus
	if not item.passive_effect_id.is_empty() and item.passive_effect_id not in equipment_passive_ids:
		equipment_passive_ids.append(item.passive_effect_id)


func has_equipment_passive(passive_id: StringName) -> bool:
	return passive_id in equipment_passive_ids


func record_normal_combat_victory() -> void:
	combats_won += 1
	run_ash += NORMAL_COMBAT_ASH


func record_elite_combat_victory() -> void:
	combats_won += 1
	elites_won += 1
	run_ash += ELITE_COMBAT_ASH


func record_boss_victory() -> void:
	run_completed = true
	run_ash += BOSS_VICTORY_ASH


## Active Run Persistence serialization. Fields intentionally NOT written
## here (dropped, not just defaulted): route_choice_count/route_option_a/
## route_option_b/chosen_destination/chosen_tile_type/route_choice_cooldown
## — confirmed dead, superseded by the deterministic fork system (see
## RouteChoiceResolver's own header comment); losing them on resume cannot
## alter gameplay, they are not read by BoardTurnController or any live
## routing path. biome_data is intentionally NOT written either — it is a
## Resource, not JSON-safe data, and is re-derived from biome_id on load
## (see from_dictionary()); a biome_id that no longer resolves is a
## content-drift case for the caller (ActiveRunRepository) to handle, not
## something this method silently papers over.
func to_dictionary() -> Dictionary:
	var route_branches_data: Dictionary = {}
	for fork_index: int in route_branches:
		var branch: RouteBranchData = route_branches[fork_index]
		if branch != null:
			route_branches_data[str(fork_index)] = branch.to_dictionary()
	return {
		"run_id": run_id,
		"started_at_unix": started_at_unix,
		"biome_id": String(biome_id),
		"board_seed": board_seed,
		"board_tile_sequence": board_tile_sequence.duplicate(),
		"route_branches": route_branches_data,
		"last_normal_encounter_signature": String(last_normal_encounter_signature),
		"biome_intro_shown": biome_intro_shown,
		"player_name": player_name,
		"active_skill_id": String(active_skill_id),
		"equipped_skill_ids": _string_names_to_strings(equipped_skill_ids),
		"equipped_companion_id": String(equipped_companion_id),
		"equipped_weapon_id": String(equipped_weapon_id),
		"equipped_armor_id": String(equipped_armor_id),
		"owned_equipment_ids_at_start": owned_equipment_ids_at_start.duplicate(),
		"max_health": max_health,
		"current_health": current_health,
		"attack": attack,
		"defense": defense,
		"board_position": board_position,
		"board_locked": board_locked,
		"active_branch": active_branch,
		"active_fork_index": active_fork_index,
		"combats_won": combats_won,
		"elites_won": elites_won,
		"events_resolved": events_resolved,
		"treasures_found": treasures_found,
		"event_flag_ids": _string_names_to_strings(event_flag_ids),
		"seen_event_ids": _string_names_to_strings(seen_event_ids),
		"resolved_event_positions": resolved_event_positions.duplicate(),
		"resolved_treasure_positions": resolved_treasure_positions.duplicate(),
		"pending_treasure_position": pending_treasure_position,
		"pending_treasure_offers": pending_treasure_offers.duplicate(true),
		"upgrades_obtained": upgrades_obtained,
		"run_completed": run_completed,
		"run_ash": run_ash,
		"biome_material_earned": biome_material_earned,
		"rewards_deposited": rewards_deposited,
		"player_xp_earned": player_xp_earned,
		"player_level_before": player_level_before,
		"player_level_after": player_level_after,
		"player_xp_before": player_xp_before,
		"player_xp_after": player_xp_after,
		"player_levels_gained": player_levels_gained,
		"completed_milestone_ids_this_run": _string_names_to_strings(completed_milestone_ids_this_run),
		"milestone_ash_awarded": milestone_ash_awarded,
		"loot_rolled": loot_rolled,
		"pending_loot_id": pending_loot_id,
		"duplicate_converted_id": String(duplicate_converted_id),
		"duplicate_ash_awarded": duplicate_ash_awarded,
		"boss_reward_id": String(boss_reward_id),
		"boss_reward_applied": boss_reward_applied,
		"boss_chest_id": String(boss_chest_id),
		"boss_chest_awarded": boss_chest_awarded,
		"guardian_sigils_awarded": guardian_sigils_awarded,
		"loot_minimum_rarity": int(loot_minimum_rarity),
		"loot_rarity_upgrades": loot_rarity_upgrades,
		"active_boons": _string_name_int_dict_to_string_dict(active_boons),
		"skill_augments": _string_name_int_dict_to_string_dict(skill_augments),
		"active_synergy_ids": _string_names_to_strings(active_synergy_ids),
		"activated_synergy_ids": _string_names_to_strings(activated_synergy_ids),
		"pending_synergy_announcement_ids": _string_names_to_strings(pending_synergy_announcement_ids),
		"upgrade_rerolls": upgrade_rerolls,
		"reward_offers_generated": reward_offers_generated,
		"phoenix_blood_empowered": phoenix_blood_empowered,
		"combat_energy_carryover": combat_energy_carryover,
		"run_level": run_level,
		"current_xp": current_xp,
		"total_xp_gained": total_xp_gained,
		"pending_level_ups": pending_level_ups,
		"level_up_choices_generated": level_up_choices_generated,
		"pending_level_up_option_ids": _string_names_to_strings(pending_level_up_option_ids),
		"run_level_upgrade_stacks": _string_name_int_dict_to_string_dict(run_level_upgrade_stacks),
		"equipment_passive_ids": _string_names_to_strings(equipment_passive_ids),
		"equipment_crit_chance": equipment_crit_chance,
		"equipment_crit_damage_bonus": equipment_crit_damage_bonus,
		"equipment_ember_gain_bonus": equipment_ember_gain_bonus,
		"equipment_healing_power_bonus": equipment_healing_power_bonus,
		"equipment_skill_damage_bonus": equipment_skill_damage_bonus,
		"equipment_resistance_bonuses": _string_name_float_dict_to_string_dict(equipment_resistance_bonuses),
		"telemetry_started": telemetry_started,
		"telemetry_finished": telemetry_finished,
		"telemetry_started_unix": telemetry_started_unix,
		"telemetry_skill_uses": telemetry_skill_uses.duplicate(),
		"telemetry_synergy_ids": _string_names_to_strings(telemetry_synergy_ids),
		"telemetry_last_boss_id": String(telemetry_last_boss_id),
		"telemetry_boss_phase_reached": telemetry_boss_phase_reached,
		"starting_option_id": String(starting_option_id),
	}


static func from_dictionary(data: Dictionary) -> RunState:
	var run := RunState.new()
	run.run_id = _read_string(data, "run_id")
	run.started_at_unix = _read_int(data, "started_at_unix", run.started_at_unix, 0, 99_999_999_999)
	run.biome_id = StringName(_read_string(data, "biome_id"))
	run.biome_data = BiomeCatalog.get_by_id(run.biome_id)
	run.board_seed = _read_int(data, "board_seed", BoardGenerator.NO_SEED, -2_000_000_000, 2_000_000_000)
	run.board_tile_sequence = _read_int_array(data, "board_tile_sequence")
	run.route_branches = _read_route_branches(data, "route_branches")
	run.last_normal_encounter_signature = StringName(_read_string(data, "last_normal_encounter_signature"))
	run.biome_intro_shown = _read_bool(data, "biome_intro_shown")
	run.player_name = _read_string(data, "player_name", run.player_name)
	run.active_skill_id = StringName(_read_string(data, "active_skill_id", String(ActiveSkillCatalog.DEFAULT_SKILL_ID)))
	run.equipped_skill_ids = _read_string_name_array(data, "equipped_skill_ids")
	run.equipped_companion_id = StringName(_read_string(data, "equipped_companion_id"))
	run.equipped_weapon_id = StringName(_read_string(data, "equipped_weapon_id"))
	run.equipped_armor_id = StringName(_read_string(data, "equipped_armor_id"))
	run.owned_equipment_ids_at_start = _read_string_array(data, "owned_equipment_ids_at_start")
	run.max_health = _read_int(data, "max_health", BASE_MAX_HEALTH, 1, 2_000_000_000)
	run.current_health = _read_int(data, "current_health", run.max_health, 0, run.max_health)
	run.attack = _read_int(data, "attack", BASE_ATTACK, 0, 2_000_000_000)
	run.defense = _read_int(data, "defense", BASE_DEFENSE, 0, 2_000_000_000)
	run.board_position = _read_int(data, "board_position", 0, 0, 2_000_000_000)
	run.board_locked = _read_bool(data, "board_locked")
	run.active_branch = _read_int(data, "active_branch", _RouteBranchData.NONE, _RouteBranchData.NONE, _RouteBranchData.ROUTE_B)
	run.active_fork_index = _read_int(data, "active_fork_index", -1, -1, 2_000_000_000)
	run.combats_won = _read_int(data, "combats_won", 0, 0, 2_000_000_000)
	run.elites_won = _read_int(data, "elites_won", 0, 0, 2_000_000_000)
	run.events_resolved = _read_int(data, "events_resolved", 0, 0, 2_000_000_000)
	run.treasures_found = _read_int(data, "treasures_found", 0, 0, 2_000_000_000)
	run.event_flag_ids = _read_string_name_array(data, "event_flag_ids")
	run.seen_event_ids = _read_string_name_array(data, "seen_event_ids")
	run.resolved_event_positions = _read_int_array(data, "resolved_event_positions")
	run.resolved_treasure_positions = _read_int_array(data, "resolved_treasure_positions")
	run.pending_treasure_position = _read_int(data, "pending_treasure_position", -1, -1, 2_000_000_000)
	run.pending_treasure_offers = _read_dict_array(data, "pending_treasure_offers")
	run.upgrades_obtained = _read_int(data, "upgrades_obtained", 0, 0, 2_000_000_000)
	run.run_completed = _read_bool(data, "run_completed")
	run.run_ash = _read_int(data, "run_ash", 0, 0, 2_000_000_000)
	run.biome_material_earned = _read_int(data, "biome_material_earned", 0, 0, 2_000_000_000)
	run.rewards_deposited = _read_bool(data, "rewards_deposited")
	run.player_xp_earned = _read_int(data, "player_xp_earned", 0, 0, 2_000_000_000)
	run.player_level_before = _read_int(data, "player_level_before", PlayerProgressionConfig.START_LEVEL, PlayerProgressionConfig.START_LEVEL, PlayerProgressionConfig.MAX_LEVEL)
	run.player_level_after = _read_int(data, "player_level_after", PlayerProgressionConfig.START_LEVEL, PlayerProgressionConfig.START_LEVEL, PlayerProgressionConfig.MAX_LEVEL)
	run.player_xp_before = _read_int(data, "player_xp_before", 0, 0, 2_000_000_000)
	run.player_xp_after = _read_int(data, "player_xp_after", 0, 0, 2_000_000_000)
	run.player_levels_gained = _read_int(data, "player_levels_gained", 0, 0, 2_000_000_000)
	run.completed_milestone_ids_this_run = _read_string_name_array(data, "completed_milestone_ids_this_run")
	run.milestone_ash_awarded = _read_int(data, "milestone_ash_awarded", 0, 0, 2_000_000_000)
	run.loot_rolled = _read_bool(data, "loot_rolled")
	run.pending_loot_id = _read_string(data, "pending_loot_id")
	run.duplicate_converted_id = StringName(_read_string(data, "duplicate_converted_id"))
	run.duplicate_ash_awarded = _read_int(data, "duplicate_ash_awarded", 0, 0, 2_000_000_000)
	run.boss_reward_id = StringName(_read_string(data, "boss_reward_id"))
	run.boss_reward_applied = _read_bool(data, "boss_reward_applied")
	run.boss_chest_id = StringName(_read_string(data, "boss_chest_id"))
	run.boss_chest_awarded = _read_bool(data, "boss_chest_awarded")
	run.guardian_sigils_awarded = _read_int(data, "guardian_sigils_awarded", 0, 0, 2_000_000_000)
	run.loot_minimum_rarity = _read_int(data, "loot_minimum_rarity", EquipmentData.Rarity.COMMON, EquipmentData.Rarity.COMMON, EquipmentData.Rarity.EPIC) as EquipmentData.Rarity
	run.loot_rarity_upgrades = _read_int(data, "loot_rarity_upgrades", 0, 0, 2_000_000_000)
	run.active_boons = _read_string_name_int_dict(data, "active_boons")
	run.skill_augments = _read_string_name_int_dict(data, "skill_augments")
	run.active_synergy_ids = _read_string_name_array(data, "active_synergy_ids")
	run.activated_synergy_ids = _read_string_name_array(data, "activated_synergy_ids")
	run.pending_synergy_announcement_ids = _read_string_name_array(data, "pending_synergy_announcement_ids")
	run.upgrade_rerolls = _read_int(data, "upgrade_rerolls", 2, 0, 2_000_000_000)
	run.reward_offers_generated = _read_int(data, "reward_offers_generated", 0, 0, 2_000_000_000)
	run.phoenix_blood_empowered = _read_bool(data, "phoenix_blood_empowered")
	run.combat_energy_carryover = _read_int(data, "combat_energy_carryover", 0, 0, 2_000_000_000)
	run.run_level = _read_int(data, "run_level", RunLevelConfig.START_LEVEL, RunLevelConfig.START_LEVEL, RunLevelConfig.MAX_RUN_LEVEL)
	run.current_xp = _read_int(data, "current_xp", 0, 0, 2_000_000_000)
	run.total_xp_gained = _read_int(data, "total_xp_gained", 0, 0, 2_000_000_000)
	run.pending_level_ups = _read_int(data, "pending_level_ups", 0, 0, 2_000_000_000)
	run.level_up_choices_generated = _read_int(data, "level_up_choices_generated", 0, 0, 2_000_000_000)
	run.pending_level_up_option_ids = _read_string_name_array(data, "pending_level_up_option_ids")
	run.run_level_upgrade_stacks = _read_string_name_int_dict(data, "run_level_upgrade_stacks")
	run.equipment_passive_ids = _read_string_name_array(data, "equipment_passive_ids")
	run.equipment_crit_chance = _read_float(data, "equipment_crit_chance")
	run.equipment_crit_damage_bonus = _read_float(data, "equipment_crit_damage_bonus")
	run.equipment_ember_gain_bonus = _read_float(data, "equipment_ember_gain_bonus")
	run.equipment_healing_power_bonus = _read_float(data, "equipment_healing_power_bonus")
	run.equipment_skill_damage_bonus = _read_float(data, "equipment_skill_damage_bonus")
	run.equipment_resistance_bonuses = _read_string_name_float_dict(data, "equipment_resistance_bonuses")
	run.telemetry_started = _read_bool(data, "telemetry_started")
	run.telemetry_finished = _read_bool(data, "telemetry_finished")
	run.telemetry_started_unix = _read_int(data, "telemetry_started_unix", 0, 0, 99_999_999_999)
	run.telemetry_skill_uses = _read_string_int_dict(data, "telemetry_skill_uses")
	run.telemetry_synergy_ids = _read_string_name_array(data, "telemetry_synergy_ids")
	run.telemetry_last_boss_id = StringName(_read_string(data, "telemetry_last_boss_id"))
	run.telemetry_boss_phase_reached = _read_int(data, "telemetry_boss_phase_reached", 0, 0, 2_000_000_000)
	run.starting_option_id = StringName(_read_string(data, "starting_option_id"))
	return run


static func _read_route_branches(data: Dictionary, key: String) -> Dictionary:
	var result: Dictionary = {}
	var raw: Variant = data.get(key, {})
	if typeof(raw) != TYPE_DICTIONARY:
		return result
	var raw_dict: Dictionary = raw
	for raw_key: Variant in raw_dict:
		var fork_index: int = int(String(raw_key)) if String(raw_key).is_valid_int() else -1
		if fork_index < 0:
			continue
		var branch_data: Variant = raw_dict[raw_key]
		if typeof(branch_data) != TYPE_DICTIONARY:
			continue
		var branch: RouteBranchData = _RouteBranchData.from_dictionary(branch_data)
		if branch != null:
			result[fork_index] = branch
	return result


static func _string_names_to_strings(values: Array[StringName]) -> Array[String]:
	var result: Array[String] = []
	for value: StringName in values:
		result.append(String(value))
	return result


static func _string_name_int_dict_to_string_dict(values: Dictionary) -> Dictionary:
	var result: Dictionary = {}
	for key: Variant in values:
		result[String(key)] = int(values[key])
	return result


static func _string_name_float_dict_to_string_dict(values: Dictionary) -> Dictionary:
	var result: Dictionary = {}
	for key: Variant in values:
		result[String(key)] = float(values[key])
	return result


static func _read_string_name_array(data: Dictionary, key: String) -> Array[StringName]:
	var result: Array[StringName] = []
	var raw: Variant = data.get(key, [])
	if typeof(raw) != TYPE_ARRAY:
		return result
	for value: Variant in raw:
		if typeof(value) == TYPE_STRING or typeof(value) == TYPE_STRING_NAME:
			result.append(StringName(String(value)))
	return result


static func _read_string_array(data: Dictionary, key: String) -> Array[String]:
	var result: Array[String] = []
	var raw: Variant = data.get(key, [])
	if typeof(raw) != TYPE_ARRAY:
		return result
	for value: Variant in raw:
		if typeof(value) == TYPE_STRING or typeof(value) == TYPE_STRING_NAME:
			result.append(String(value))
	return result


static func _read_int_array(data: Dictionary, key: String) -> Array[int]:
	var result: Array[int] = []
	var raw: Variant = data.get(key, [])
	if typeof(raw) != TYPE_ARRAY:
		return result
	for value: Variant in raw:
		if typeof(value) == TYPE_INT or typeof(value) == TYPE_FLOAT:
			result.append(int(value))
	return result


static func _read_dict_array(data: Dictionary, key: String) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	var raw: Variant = data.get(key, [])
	if typeof(raw) != TYPE_ARRAY:
		return result
	for value: Variant in raw:
		if typeof(value) == TYPE_DICTIONARY:
			result.append((value as Dictionary).duplicate(true))
	return result


static func _read_string_name_int_dict(data: Dictionary, key: String) -> Dictionary[StringName, int]:
	var result: Dictionary[StringName, int] = {}
	var raw: Variant = data.get(key, {})
	if typeof(raw) != TYPE_DICTIONARY:
		return result
	var raw_dict: Dictionary = raw
	for raw_key: Variant in raw_dict:
		var raw_value: Variant = raw_dict[raw_key]
		if typeof(raw_value) == TYPE_INT or typeof(raw_value) == TYPE_FLOAT:
			result[StringName(String(raw_key))] = int(raw_value)
	return result


static func _read_string_int_dict(data: Dictionary, key: String) -> Dictionary[String, int]:
	var result: Dictionary[String, int] = {}
	var raw: Variant = data.get(key, {})
	if typeof(raw) != TYPE_DICTIONARY:
		return result
	var raw_dict: Dictionary = raw
	for raw_key: Variant in raw_dict:
		var raw_value: Variant = raw_dict[raw_key]
		if typeof(raw_value) == TYPE_INT or typeof(raw_value) == TYPE_FLOAT:
			result[String(raw_key)] = int(raw_value)
	return result


static func _read_string_name_float_dict(data: Dictionary, key: String) -> Dictionary[StringName, float]:
	var result: Dictionary[StringName, float] = {}
	var raw: Variant = data.get(key, {})
	if typeof(raw) != TYPE_DICTIONARY:
		return result
	var raw_dict: Dictionary = raw
	for raw_key: Variant in raw_dict:
		var raw_value: Variant = raw_dict[raw_key]
		if typeof(raw_value) == TYPE_INT or typeof(raw_value) == TYPE_FLOAT:
			result[StringName(String(raw_key))] = float(raw_value)
	return result


static func _read_string(data: Dictionary, key: String, default_value: String = "") -> String:
	var value: Variant = data.get(key, default_value)
	return value if typeof(value) == TYPE_STRING else default_value


static func _read_bool(data: Dictionary, key: String, default_value: bool = false) -> bool:
	var value: Variant = data.get(key, default_value)
	return bool(value) if typeof(value) == TYPE_BOOL else default_value


static func _read_float(data: Dictionary, key: String, default_value: float = 0.0) -> float:
	var value: Variant = data.get(key, default_value)
	if typeof(value) != TYPE_INT and typeof(value) != TYPE_FLOAT:
		return default_value
	var result: float = float(value)
	return default_value if (is_nan(result) or is_inf(result)) else result


static func _read_int(data: Dictionary, key: String, default_value: int, minimum: int, maximum: int) -> int:
	if not data.has(key):
		return default_value
	var value: Variant = data[key]
	if typeof(value) != TYPE_INT and typeof(value) != TYPE_FLOAT:
		return default_value
	if typeof(value) == TYPE_FLOAT and (is_nan(value) or is_inf(value)):
		return default_value
	return clampi(int(value), minimum, maximum)
